### ISSUE TITLE
init admin's password when it has init password "123456"

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-rethinkdb#18]
touch rethindb.py
```
from rethinkdb import r
r.connect(password='123456').repl()
r.db('rethinkdb').table('users').get('admin').update({'password': '$newpassword'}).run()
```

role_init run this file by pyhon3, and delete it

**Comment by qiaofeng1227** [comment]
```

```[root@iZj6c1yri0h6irbq6cuqksZ ~]# rethinkdb repl  --host
Usage: rethinkdb-repl [options]

rethinkdb-repl: error: --host-name option requires 1 argument
[root@iZj6c1yri0h6irbq6cuqksZ ~]# rethinkdb repl  --host=localhost
The RethinkDB driver has been imported as `r`.
Warning: Could not connect to localhost:28015, Wrong password
==========
>>> 
now exiting InteractiveConsole...
[root@iZj6c1yri0h6irbq6cuqksZ ~]# rethinkdb repl  --host=localhost --password=123456
Usage: rethinkdb-repl [options]

rethinkdb-repl: error: --password option does not take a value
[root@iZj6c1yri0h6irbq6cuqksZ ~]# rethinkdb repl  --host=localhost --password='123456'
Usage: rethinkdb-repl [options]

rethinkdb-repl: error: --password option does not take a value
[root@iZj6c1yri0h6irbq6cuqksZ ~]# rethinkdb repl  --host=localhost --password
Password for `admin`: 
Traceback (most recent call last):
  File "/usr/local/bin/rethinkdb-repl", line 8, in <module>
    sys.exit(startInterpreter())
  File "/usr/local/lib/python3.6/site-packages/rethinkdb/__main__.py", line 41, in startInterpreter
    argv if argv is not None else sys.argv[1:], connect=False
  File "/usr/local/lib/python3.6/site-packages/rethinkdb/utils_common.py", line 432, in parse_args
    options, args = super(CommonOptionsParser, self).parse_args(*args, **kwargs)
  File "/usr/lib64/python3.6/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib64/python3.6/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib64/python3.6/optparse.py", line 785, in process
    self.action, self.dest, opt, value, values, parser)
  File "/usr/local/lib/python3.6/site-packages/rethinkdb/utils_common.py", line 311, in take_action
    values[dest] = getpass.getpass("Password for `admin`: ")
TypeError: 'Values' object does not support item assignment

**Comment by chendelin1982** [comment]
Final solution
```
[root@iZj6cci77g4mwxvavoas3qZ ~]# echo "123456" > /tmp/pw
[root@iZj6cci77g4mwxvavoas3qZ ~]# rethinkdb repl --password-file /tmp/pw
```
